# Generated by Django 4.1.4 on 2022-12-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2022-04-23'),
            preserve_default=False,
        ),
    ]
